name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name：install aarch64-linux-gnu
      run： apt -y install gcc-aarch64-linux-gnu
    - name: make
      run: make
