name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: make
      run: sudo apt -y install gcc-aarch64-linux-gnu && make

    - name : upload bin
      uses: actions/upload-artifact@master
      if: always()
      with:
          name: rawcapture
          path: ${{ github.workspace }}/rawcapture
          
